services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - home_assistant
    restart: unless-stopped
    privileged: true
    network_mode: host
  ha-alexa-shopping-list-sync:
    image: "madmachinations/ha-alexa-shopping-list-sync:latest"
    volumes:
      - ./alexa-config:/config
    ports:
      - 4000:4000
    networks:
      - home_assistant

networks:
  home_assistant:
